spring:
  application:
    name: payment-service

server:
  port: 8085

app:
  jwt:
    secret: ${JWT_SECRET:NOvxdE/9L4Mn4dKRSzIcGNnHjf3gdtdTopmti0n7Dy4=}
    expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
