apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: app
        image: ghcr.io/kenyereskrisztian/payment-service:latest
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: payment-service-configmap
        - secretRef:
            name: ecommerce-shared-secret
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
